--- #YAML:1.0
name: Authen-Libwrap
version: 0.21
author:
  - |-
    James FitzGibbon, E<lt>jfitz@CPAN.orgE<gt>
    =head1 COPYRIGHT
abstract: access to Wietse Venema's TCP Wrappers library
license: perl
requires:
  Scalar::Util: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Authen::Libwrap:
    file: lib/Authen/Libwrap.pm
    version: 0.21
generated_by: Module::Build version 0.25_02
