--- #YAML:1.0
name: Authen-Libwrap
version: 0.20
license: perl
distribution_type: module
requires:
  Scalar::Util: 0
recommends: {}
build_requires:
  Test::Exception: 0
  Test::More: 0
conflicts: {}
provides:
  Authen::Libwrap:
    file: lib/Authen/Libwrap.pm
    version: 0.2
generated_by: Module::Build version 0.21
