--- #YAML:1.0
name: Authen-Libwrap
version: 0.11
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Authen::Libwrap:
    file: lib/Authen/Libwrap.pm
    version: 0.11
generated_by: Module::Build version 0.21
